### ISSUE TITLE
epic: Multi-lingual Ichigo

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/ichigo#116]
## Goal
Expand Ichigo model's capabilities to support multiple Asian languages (and more), with initial focus on Vietnamese and Singlish, achieving production-grade speech recognition and synthesis quality.

### Current State
- Ichigo model currently supports English language only
- Limited ability to handle Asian language phonemes and tonal variations

### Proposed Solution
- Develop a multi-lingual speech foundation model based on WhisperSpeech approach
- Training Speech Encoder for Asian languages

### Multi-lingual Base
- LibriSpeech (English baseline)
- Common Voice (Multi-language)
- GigaSpeech (Vie, Thai & Indo)
- FLEURS (1000+ hours, 102 languages)
- ... etc

### Language-Specific
- Vietnamese
  - ViVoice (100+ hours)
  - BUD500 (500 hours)
  - ... etc 
   
- Singlish
  - National Speech Corpus (NSC)

## Reference:
- WhisperSpeech: https://github.com/collabora/WhisperSpeech
- PhoWhisper: https://github.com/VinAIResearch/PhoWhisper

## Tasklist
- [ ] Dataset Collection & Preprocessing (Issue: )
- [ ] WhisperVQ Development (Issue: )
- [ ] Multi-lingual Instruct Speech Dataset Creation (Issue: )
- [ ] Ichigo Training (Issue: )
- [ ] VietTTS (Issue: )

**Comment by bachvudinh** [comment]
help
