### ISSUE TITLE
task: Dataset Collection & Preprocessing

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/ichigo#118]
## Goal
Gathering all the data opensource available for the first multilingual training run. This test will focus mostly in Vietnamese dataset.

### Multi-lingual Base
- [ ] LibriSpeech: https://huggingface.co/datasets/facebook/multilingual_librispeech or check parler-tss for the cleaned version: https://huggingface.co/datasets/parler-tts/libritts_r_filtered
- [ ] Common Voice (choose subset of langs): https://huggingface.co/datasets/mozilla-foundation/common_voice_17_0
- [ ] GigaSpeech2 Refined (Vie, Thai & Indo) (cc Jiaqi for the refined version): https://huggingface.co/datasets/speechcolab/gigaspeech2
- [ ] FLEURS (choose subset of langs): https://huggingface.co/datasets/google/fleurs
- [ ] Emilia (choose subset of langs): https://huggingface.co/datasets/amphion/Emilia-Dataset
- ...

### Vietnamese
- [ ] ViVoice (100+ hours) https://huggingface.co/datasets/linhtran92/viet_bud500
- [ ] BUD500 (500 hours): https://huggingface.co/datasets/linhtran92/viet_bud500
- [ ] VLSP (100 hours): https://huggingface.co/datasets/quocanh34/viet_vlsp

### Singlish
- [ ] National Speech Corpus (NSC)

**Comment by tuanlda78202** [comment]
These datasets will be saved on S3 (which can be useful for connecting RunPod later) and will be saved on disk with the A6000s cluster for training Quantizer Whisper Encoder and Ichigo.

**Comment by tuanlda78202** [comment]
Downloaded full dataset from HF and upload to S3, check [it](https://github.com/janhq/datasets/actions/runs/11958116576/job/33336886016)!

**Comment by tikikun** [comment]
is this duplication?

**Comment by dan-homebrew** [comment]
Can we add the license information next to each dataset - I am concerned that we are using some datasets that are non-commercial licensed

**Comment by tuanlda78202** [comment]
Just update license information for each dataset!

**Comment by hahuyhoang411** [comment]
All good thanks @tuanlda78202
